### ISSUE TITLE
Location calculator for each pìece of image not working.

### ISSUE THREAD

**Issue by MetalGearDaner** [Coutume/ImageOnMap#2]
Whenever you use the command /tomap URL, the plugin will divide the image into diferent pieces in a specific order set as X:X with the text: "Scaling at X:X", as usual. In the latest version of the project compiled directly from the source code, it will only tell you that each piece are "Scaling at 1:8 / (Leve 3/4)". Here is a proof of it:

http://prntscr.com/64zqhf

Here is the console log of the problem:

http://paste.ofcode.org/sRGyGnbr2iGZZirfWbQE8k

Also, the translation aren't working appropiately, as you can see in the proof, there are some unknown characters on the message.

With this problem, the user is unable to know easily where he has to put each piece (map) of the image.

**Comment by prokopyl** [comment]
Fixed in bdf35e9eef3eeb353a03c13904ffb93170860800.

**Comment by MetalGearDaner** [comment]
Still happening with the build from jenkins.

http://prntscr.com/67ka8y

**Comment by prokopyl** [comment]
Jenkins builds were not up to date, only the last commit triggered it correctly.
http://jenkins.carrade.eu/job/ImageOnMap/lastSuccessfulBuild/artifact/target/ImageOnMap-2.99.jar
This build has the fix for this issue, but the previous ones don't.

**Comment by MetalGearDaner** [comment]
Thank you
